spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.gruelbox: TRACE